import sqlite3
conn = sqlite3.connect('lenta_products.db')
c = conn.cursor()
c.execute('SELECT name FROM site_products LIMIT 5')
print('Первые 5:', [r[0] for r in c.fetchall()])
c.execute("SELECT name FROM site_products WHERE name LIKE '%АГДАМ%' LIMIT 3")
print('АГДАМ:', [r[0] for r in c.fetchall()])
c.execute("SELECT name FROM site_products WHERE name LIKE '%ХЕРЕС%' LIMIT 3")
print('ХЕРЕС:', [r[0] for r in c.fetchall()])
c.execute("SELECT name FROM site_products WHERE name LIKE '%TIO%' LIMIT 3")
print('TIO:', [r[0] for r in c.fetchall()])
conn.close()
